package MeetingApp;
// Generated Feb 22, 2017 8:53:42 PM by Hibernate Tools 4.3.1



/**
 * Participant generated by hbm2java
 */
public class Participant  implements java.io.Serializable {


     private Integer participantId;
     private String participantName;
     private String participantEmail;
     private int statusId;

    public Participant() {
    }

    public Participant(String participantName, String participantEmail, int statusId) {
       this.participantName = participantName;
       this.participantEmail = participantEmail;
       this.statusId = statusId;
    }
   
    public Integer getParticipantId() {
        return this.participantId;
    }
    
    public void setParticipantId(Integer participantId) {
        this.participantId = participantId;
    }
    public String getParticipantName() {
        return this.participantName;
    }
    
    public void setParticipantName(String participantName) {
        this.participantName = participantName;
    }
    public String getParticipantEmail() {
        return this.participantEmail;
    }
    
    public void setParticipantEmail(String participantEmail) {
        this.participantEmail = participantEmail;
    }
    public int getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }




}


