package MeetingApp;
// Generated Feb 22, 2017 8:53:42 PM by Hibernate Tools 4.3.1



/**
 * ParticipantMeeting generated by hbm2java
 */
public class ParticipantMeeting  implements java.io.Serializable {


     private ParticipantMeetingId id;

    public ParticipantMeeting() {
    }

    public ParticipantMeeting(ParticipantMeetingId id) {
       this.id = id;
    }
   
    public ParticipantMeetingId getId() {
        return this.id;
    }
    
    public void setId(ParticipantMeetingId id) {
        this.id = id;
    }




}


