package MeetingApp;
// Generated Feb 22, 2017 8:53:42 PM by Hibernate Tools 4.3.1



/**
 * ParticipantMeetingId generated by hbm2java
 */
public class ParticipantMeetingId  implements java.io.Serializable {


     private int participantId;
     private int meetingId;

    public ParticipantMeetingId() {
    }

    public ParticipantMeetingId(int participantId, int meetingId) {
       this.participantId = participantId;
       this.meetingId = meetingId;
    }
   
    public int getParticipantId() {
        return this.participantId;
    }
    
    public void setParticipantId(int participantId) {
        this.participantId = participantId;
    }
    public int getMeetingId() {
        return this.meetingId;
    }
    
    public void setMeetingId(int meetingId) {
        this.meetingId = meetingId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParticipantMeetingId) ) return false;
		 ParticipantMeetingId castOther = ( ParticipantMeetingId ) other; 
         
		 return (this.getParticipantId()==castOther.getParticipantId())
 && (this.getMeetingId()==castOther.getMeetingId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getParticipantId();
         result = 37 * result + this.getMeetingId();
         return result;
   }   


}


