package MeetingApp;
// Generated Feb 22, 2017 8:53:42 PM by Hibernate Tools 4.3.1



/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private int statusId;
     private String statusType;

    public Status() {
    }

    public Status(int statusId, String statusType) {
       this.statusId = statusId;
       this.statusType = statusType;
    }
   
    public int getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }
    public String getStatusType() {
        return this.statusType;
    }
    
    public void setStatusType(String statusType) {
        this.statusType = statusType;
    }




}


